version: '3.9'
services:
  models-gate-tracker:
    build: 
      dockerfile: ./Dockerfile.dev
    # command: python3.7 /app/server.py
    runtime: nvidia
    environment:
      ENV_ID: dev
      CUDA_VISIBLE_DEVICES: 1
      TF_FORCE_GPU_ALLOW_GROWTH: true
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 9100:9100
    volumes:
      - .:/app/
#      - bee-video-volume:/app/tmp
#    network_mode: bridge
    tty: true
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - gratheon

networks:
  gratheon:

    #volumes:
    #bee-video-volume:
