FROM nvidia/cuda:12.3.1-base-ubuntu20.04

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PROJ_DIR=/usr

RUN apt update && apt upgrade -y

RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3.7-dev

RUN apt-get install -y apt-utils libsm6 libxext6 libxrender-dev libglib2.0-0
RUN apt-get install -y python3-apt python3-setuptools
RUN apt-get install -y python3-opengl python3.7-distutils
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-wheel

RUN apt install -y gcc

RUN pip install --upgrade pip
RUN python3 -m pip install setuptools wheel

COPY . /app/
COPY requirements.txt /app/requirements.txt

#RUN GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true pip install --no-cache-dir --force-reinstall -Iv grpcio==1.36.1
RUN python3.7 -m pip install -r requirements.txt


EXPOSE 9100

CMD ["python3.7", "/app/server.py"]
